export enum ToeicQuestionTopic {
  GRAMMAR = 'GRAMMAR',
  VOCABULARY = 'VOCABULARY',
  COMPREHENSION = 'COMPREHENSION',
  LISTENING_DETAIL = 'LISTENING_DETAIL',
  LISTENING_INFERENCE = 'LISTENING_INFERENCE',
}
