export const quizMockData = [
  {
    status: 'COMPLETED',
    score: 100,
    questionsCount: 10,
    correctCount: 10,
    daysAgo: 5,
  },
  {
    status: 'COMPLETED',
    score: 80,
    questionsCount: 10,
    correctCount: 8,
    daysAgo: 4,
  },
  {
    status: 'COMPLETED',
    score: 60,
    questionsCount: 15,
    correctCount: 9,
    daysAgo: 3,
  },
  {
    status: 'COMPLETED',
    score: 40,
    questionsCount: 10,
    correctCount: 4,
    daysAgo: 2,
  },
  {
    status: 'IN_PROGRESS',
    score: 0,
    questionsCount: 10,
    correctCount: 0,
    daysAgo: 1,
  },
  {
    status: 'COMPLETED',
    score: 90,
    questionsCount: 20,
    correctCount: 18,
    daysAgo: 1,
  },
  {
    status: 'IN_PROGRESS',
    score: 0,
    questionsCount: 15,
    correctCount: 0,
    daysAgo: 0,
  },
  {
    status: 'PENDING',
    score: 0,
    questionsCount: 10,
    correctCount: 0,
    daysAgo: 0,
  },
  {
    status: 'COMPLETED',
    score: 75,
    questionsCount: 20,
    correctCount: 15,
    daysAgo: 2,
  },
  {
    status: 'IN_PROGRESS',
    score: 0,
    questionsCount: 15,
    correctCount: 0,
    daysAgo: 1,
  },
];
