export const articleData = [
  {
    title: 'The Future of Artificial Intelligence in Education',
    content: `Artificial intelligence is rapidly transforming the educational landscape. From personalized learning paths to automated grading systems, AI technologies are making education more accessible and efficient.\n\nTeachers are now able to utilize AI-driven analytics to identify students who are struggling and provide targeted interventions. Furthermore, natural language processing tools are helping students improve their writing skills by offering real-time feedback.\n\nHowever, the integration of AI in education also raises ethical concerns. Issues regarding data privacy and the potential for algorithmic bias must be carefully addressed. As we move forward, it is crucial to find a balance between technological innovation and human empathy in the classroom.`,
    author: 'Dr. Sarah Jenkins',
    source: 'TechEdu Quarterly',
    category: 'Technology',
    difficultyLevel: 'B2',
    imageUrl:
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
    tags: ['ai', 'education', 'future'],
    isPublished: true,
  },
  {
    title: 'Mastering the TOEIC: Tips for Success',
    content: `Achieving a high score on the TOEIC requires more than just a good grasp of English grammar and vocabulary; it demands strategic preparation.\n\nFirstly, familiarize yourself with the test format. Knowing what to expect in each section will reduce anxiety and save valuable time. Secondly, practice active listening. Expose yourself to various English accents, as the TOEIC features speakers from North America, the UK, and Australia.\n\nFinally, manage your time wisely during the reading section. Don't spend too long on a single question. If you are unsure, make an educated guess and move on. Regular practice with mock tests is the most effective way to build stamina and improve your overall performance.`,
    author: 'Michael Thompson',
    source: 'Lumen Learning Guide',
    category: 'Education',
    difficultyLevel: 'B1',
    imageUrl:
      'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=800&q=80',
    tags: ['toeic', 'tips', 'study'],
    isPublished: true,
  },
  {
    title: 'Global Supply Chain Disruptions: A 2024 Overview',
    content: `The global supply chain continues to face significant headwinds in 2024. Geopolitical tensions, extreme weather events, and shifting consumer demands have all contributed to ongoing volatility.\n\nCompanies are increasingly recognizing the need to move away from just-in-time inventory systems toward more resilient, buffer-heavy models. This paradigm shift requires significant capital investment and a complete overhaul of logistics planning.\n\nFurthermore, the push for sustainability is forcing businesses to re-evaluate their suppliers. Tracking carbon footprints and ensuring ethical labor practices across the supply chain is no longer just a PR exercise, but a regulatory requirement in many regions.`,
    author: 'David Chen',
    source: 'Business Logistics Journal',
    category: 'Business',
    difficultyLevel: 'C1',
    imageUrl:
      'https://images.unsplash.com/photo-1586528116311-ad8ed7c663e0?auto=format&fit=crop&w=800&q=80',
    tags: ['business', 'logistics', 'global'],
    isPublished: true,
  },
  {
    title: 'The Psychology of Productivity',
    content: `Why do we struggle to get things done even when we know they are important? The answer lies not in a lack of willpower, but in our psychology.\n\nProcrastination is often a coping mechanism for stress or anxiety related to the task itself. When a task feels overwhelming, our brain seeks immediate relief by switching to something easier, like scrolling through social media.\n\nTo combat this, psychologists recommend breaking large projects into impossibly small steps. Instead of "Write the report," try "Open a new document and write one sentence." This minimizes the perceived threat and allows momentum to build naturally.`,
    author: 'Elena Rodriguez',
    source: 'Mind & Work Magazine',
    category: 'Psychology',
    difficultyLevel: 'B2',
    imageUrl:
      'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=800&q=80',
    tags: ['productivity', 'psychology', 'work'],
    isPublished: true,
  },
  {
    title: 'Sustainable Architecture: Building for Tomorrow',
    content: `Modern architecture is undergoing a green revolution. The focus has shifted from constructing purely aesthetic structures to building spaces that actively contribute to environmental conservation.\n\nArchitects are now utilizing innovative materials such as cross-laminated timber and recycled steel. Additionally, passive design principles are being employed to maximize natural light and ventilation, thereby significantly reducing energy consumption.\n\nThe concept of "living buildings" is also gaining traction. These structures are designed to generate their own energy, capture and treat their own water, and operate completely seamlessly within their natural surroundings without pollution.`,
    author: 'Marcus Vance',
    source: 'Architectural Digest Modern',
    category: 'Environment',
    difficultyLevel: 'B2',
    imageUrl:
      'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=800&q=80',
    tags: ['architecture', 'sustainability', 'environment'],
    isPublished: true,
  },
  {
    title: 'Effective Communication in Remote Teams',
    content: `As remote work becomes a permanent fixture for many companies, mastering virtual communication is an essential skill for professionals.\n\nOne of the biggest challenges in remote teams is the loss of non-verbal cues. Nuance is easily lost in text-based communication, leading to misunderstandings. Therefore, it is crucial to default to over-communication and provide explicit context in messages.\n\nMoreover, establishing clear guidelines for different communication channels can boost efficiency. For instance, using instant messaging for quick questions, emails for formal updates, and video calls for complex discussions or brainstorming sessions helps prevent notification fatigue.`,
    author: 'Jessica Lee',
    source: 'Remote Work Today',
    category: 'Business',
    difficultyLevel: 'B1',
    imageUrl:
      'https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=800&q=80',
    tags: ['remote', 'communication', 'business'],
    isPublished: true,
  },
  {
    title: 'The Rise of Plant-Based Diets',
    content: `Over the past decade, plant-based diets have transitioned from a niche lifestyle choice to a mainstream global movement. This shift is driven by a combination of health, environmental, and ethical concerns.\n\nResearch has consistently linked plant-based diets to lower risks of heart disease, hypertension, and certain types of cancer. Simultaneously, consumers are becoming increasingly aware of the significant carbon footprint associated with industrial animal agriculture.\n\nThe food industry has responded rapidly to this trend. Supermarket shelves are now stocked with plant-based alternatives to meat, dairy, and even seafood, making it easier than ever for individuals to reduce their consumption of animal products.`,
    author: 'Dr. Alan Green',
    source: 'Health & Nutrition Weekly',
    category: 'Health',
    difficultyLevel: 'B1',
    imageUrl:
      'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    tags: ['health', 'diet', 'environment'],
    isPublished: true,
  },
  {
    title: 'Understanding Cryptocurrency and Blockchain',
    content: `Cryptocurrency has sparked intense debate in the financial world, with opinions ranging from revolutionary technology to speculative bubble. At the heart of this phenomenon is blockchain technology.\n\nA blockchain is essentially a decentralized, distributed ledger that records transactions across many computers. This ensures that the record cannot be altered retroactively without the alteration of all subsequent blocks, providing a high level of security and transparency.\n\nWhile Bitcoin remains the most famous cryptocurrency, the underlying blockchain technology is being explored for various other applications, including smart contracts, supply chain tracking, and secure voting systems.`,
    author: 'Samantha Wright',
    source: 'Financial Times Tech',
    category: 'Technology',
    difficultyLevel: 'C1',
    imageUrl:
      'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&w=800&q=80',
    tags: ['crypto', 'blockchain', 'finance'],
    isPublished: true,
  },
  {
    title: 'The Art of Public Speaking',
    content: `Public speaking is consistently ranked as one of the most common fears, yet it is a vital skill for career advancement. The good news is that effective public speaking is an art that can be learned.\n\nThe foundation of a great speech is a compelling narrative. Audiences are naturally drawn to stories, so weaving personal anecdotes or relevant case studies into your presentation can significantly increase engagement.\n\nBody language also plays a crucial role. Maintaining eye contact, using purposeful hand gestures, and controlling your tone of voice convey confidence and authority. Remember, preparation is the key to overcoming anxiety; practice your speech until it flows naturally.`,
    author: 'Thomas Baker',
    source: 'Communication Masters',
    category: 'Self-Improvement',
    difficultyLevel: 'B2',
    imageUrl:
      'https://images.unsplash.com/photo-1475721028070-2051152cbcce?auto=format&fit=crop&w=800&q=80',
    tags: ['speaking', 'career', 'skills'],
    isPublished: true,
  },
  {
    title: 'Renewable Energy: Solar vs. Wind Power',
    content: `As the world transitions away from fossil fuels, solar and wind power have emerged as the leading sources of renewable energy. Both offer significant environmental benefits, but they also have distinct characteristics.\n\nSolar power is highly versatile. Solar panels can be installed on residential rooftops or scaled up to massive solar farms. However, energy generation is dependent on sunlight, requiring efficient battery storage solutions for nighttime use.\n\nWind power, on the other hand, is highly efficient in areas with consistent wind patterns, such as coastal regions or open plains. Wind turbines can generate electricity day and night, but they require significant upfront investment and have sparked debates regarding visual impact and noise.`,
    author: 'Emily Chen',
    source: 'Green Energy Today',
    category: 'Environment',
    difficultyLevel: 'B2',
    imageUrl:
      'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    tags: ['energy', 'environment', 'science'],
    isPublished: true,
  },
];
